# Refer https://docs.halo.run/developer-guide/plugin/basics/manifest

apiVersion: plugin.halo.run/v1alpha1
kind: Plugin
metadata:
  # The name defines how the plugin is invoked, A unique name
  name: article-id-management
spec:
  enabled: true
  requires: ">=2.22.0"
  author:
    name: bi1kbu
    website: https://github.com/bi1kbu
  logo: logo.png
  homepage: https://github.com/bi1kbu/article-id-management#readme
  repo: https://github.com/bi1kbu/article-id-management
  issues: https://github.com/bi1kbu/article-id-management/issues
  displayName: "文件编号管理"
  description: "本插件用于文件编号管理、文档编号管理，由机魂社（MSIEFA.ORG）开发"
  license:
    - name: "MIT"
      url: "https://opensource.org/licenses/MIT"
